### ISSUE TITLE
Shake to show solution doesn't actually turn off

### ISSUE THREAD

**Issue by superm1** [samuelmr/pebble-solveit#2]
I tried to change the setting for shake to show solution, but it doesn't seem to be effective.  I still shake and it switches between solution and problem.

I also tried switching watch faces twice to see if it would resend the data, but it still didn't seem to work properly.

**Comment by samuelmr** [comment]
Thanks Mario!

I was about to modify the shake setting anyway, and did it now. Please check if c0b59ba  solves the issue for you. (Works for me.)

**Comment by samuelmr** [comment]
No, the issue persists. For some reason the `clear` boolean evaluates to 50 every once in a while...

**Comment by superm1** [comment]
Hmm, upgrading to 2.1 today I haven't seen it yet, but it looks like 2.1 doesn't yet have that commit.

I don't have the SDK set up for local builds. If you need me to do that and check, let me know.

**Comment by samuelmr** [comment]
Strange. What does your settings screen look like?

There should be no need to build yourself.
